### ISSUE TITLE
[Enhancement] Download translations on first install

### ISSUE THREAD

**Issue by kraftner** [inpsyde/wp-translation-downloader#1]
Currently translations are only downloaded when a package is installed or updated. But if you didn't add `wp-translation-downloader` from the very beginning, translations do not get downloaded at all until a package gets updated.

I see three approaches:

1. Won't fix: One should install this package in the beginning. 😭
2. Add a possibility to manually trigger download of all translations, e.g. with an additional composer command. 🙂
3. Download all packages automatically when `wp-translation-downloader` is first installed. 😍

Concerning 3 I have admittedly never really looked into the internals of Composer, hence I am not sure if the `post-package-install` event already gets triggered on this Plugins own installation. But if yes I'd assume this would be the perfect way to then loop through all required packages and download translations.

**Comment by tyrann0us** [comment]
As a workaround, you could delete `wp-content/plugins/`/`wp-content/themes/` and run `composer install`. `wp-translation-downloader` should then download language files for all packages.

**Comment by kraftner** [comment]
:smile: Thanks, I figured that out myself, but good to mention it here too. :+1:

**Comment by MaximeCulea** [comment]
Hi there 👋 

Option 3 seems like overkill since we have to manually configure the extras :P
For me, the second option seems legit, to have the possibility to manually lunch it. It could also be a solution in some cases to check if any new translations or whatever. Because GlotPress new translations are not related to plugins update.

Just my feedback on this, good job anyway! ;)

**Comment by Chrico** [comment]
Howdy. Sorry for beeing very very very late 😬 

With the latest changes in `dev-master` i implemented the possibility to configure `'auto-run': false` and instead running the download via command manually. Checkout the README here: https://github.com/inpsyde/wp-translation-downloader#commands

Release will hopefully come this week. Depending on feedback from my colleagues ( @tyrann0us ). ;)

**Comment by Chrico** [comment]
okay, after >100 deploys on real projects, this works pretty stable. Even locally it works command-wise like it should. :-) I created a new release 1.1 which contains those features.

If there is nothing "against" it, i'll close this ticket soon @kraftner / @MaximeCulea  ;-)

**Comment by MaximeCulea** [comment]
:+1: I'll watch if the dev-master change something on my #3 issue. Thx!
