### ISSUE TITLE
Excludes are not working

### ISSUE THREAD

**Issue by johnbillion** [inpsyde/wp-translation-downloader#10]
**Describe the bug**

The `excludes` config option is not functional.

**To Reproduce**

1. Follow the instructions in [the Exclude specific packages section of the project readme](https://github.com/inpsyde/wp-translation-downloader#exclude-specific-packages), except:
   - `wpackagist-plugin/wordpress-seo` doesn't exist
   - I'm using `inpsyde/wp-translation-downloader` at version `^1`
2. Run `composer install`
3. Observe that WP Translation Downloader attempts to fetch translations for `google-tag-manager` despite it being excluded by the `inpsyde/*` rule

**Expected behavior**

WP Translation Downloader should not attempt to fetch translations for excluded depdencies.

**System (please complete the following information):**
 - OS: macOS 10.15.6
 - Composer v1

**Comment by Chrico** [comment]
Hey @johnbillion !

Sorry for the late response. Just couldn't find much time to investigate that. It seems the call for `$this->pluginConfig->doExclude()` was missing in the update-logic. 

I've add a fix for this in `1.x`-branch. Could you pls verify that everything now works for you? :-) The same fix was applied to `dev-master` (version 2.x) including a Behat test to verify that the example from README actually works as described. See here: https://github.com/inpsyde/wp-translation-downloader/commit/45cc1ca528f379d5eea3fb1ba983c0a16dc7c6f8

Btw..you can switch to `"inpsyde/wp-translation-downloader": "^2.0"`,  we're still supporting Composer v1 in this version. :-)

**Comment by johnbillion** [comment]
Thanks! That's working nicely.

**Comment by Chrico** [comment]
Perfect! Created a new release 1.2.3 for the 1.x branch as well. 👍
