### ISSUE TITLE
Option to skip installing languages

### ISSUE THREAD

**Issue by johnbillion** [inpsyde/wp-translation-downloader#11]
**Is your feature request related to a problem? Please describe.**

WP Translation Downloader attempts to download translations every time `composer install` runs. It would be great if it didn't, because on a site with a large number of dependencies it can get slow.

**Describe the solution you'd like**

Some options:

1. Only attempt to download translations when the version number of a dependency changes
2. Only attempt to download translation when running `composer update` or when running `composer install` for the first time
3. Provide a flag that can be used when installing, which enables or disables fetching translations

**Comment by Chrico** [comment]
Hey @johnbillion !

Thanks for your issue. 

To your suggestions - from bottom to top:

----

**3. Flag to enable/disable fetching translations**
You can use the `"auto-run": false`-option to only install translation files manually via CLI command `composer wp-translation-downloader:download`.
--> Is this what you're searching for? :-)

----

**2. Only install when package is installed first time or changed**
Hmm this could be also an option or configuration, to kind of "restrict" `wp-translation-downloader` to only be executed for packages which were actually installed the first time or updated. But would probably also cause problems on non-production envs, where you mostly will end up using `dev-master` and trying to fetch latest commit.

----

**1. Only when version changes**

Kind of similar to the 2., when we're using `dev-master`. But currently it's a bit hard to keep track of the installed packages and corrosponding translations which were downloaded. This can actually end really...differently:

✔️ package changed -> newest translations fetched as well.
❌ package changed -> no new(er) translations available.
✔️ package not changed -> nothing will happen -> new translations available and downloaded.
❌ package not changed -> nothing will happen -> new translations available but not downloaded.

I started to resolve this in the past, but it was quiet hard to implement - also due missing compatbility between different API's.  That's also one reason why i implemented `"auto-run": false` and the local cache to speed up local development but still being able to deploy projects and download translations.

Another major problem is, that we cannot ensure to have the correct matching versions of the translation to what is defined in composer.json for the package. As an example: The WordPress Translation API tries to resolve the given version to match to the latest available version - expect you're using e.G. `dev-master`. On a custom installation of https://github.com/GlotPress/GlotPress-WP the version is not resolved at all. It just returns the latest available version - even asking with `dev-master`.

|composer.json require|API Endpoint|Note|
|---|---|---|
|`"johnpbloch/wordpress-core": "5.6.*"`| https://api.wordpress.org/translations/core/1.0/?version=5.6.2 |works, but you can see that "ary" is in version 4.8.15|
|`"johnpbloch/wordpress-core": "700"`| https://api.wordpress.org/translations/core/1.0/?version=700 |latest (highest) available version matches|
|`"johnpbloch/wordpress-core": "dev-master"`|https://api.wordpress.org/translations/core/1.0/?version=dev-master|nothing, the API does not know what this is|

----

Hm...by writing this response I'm kind of wondering why run-time is that slow. Normally translations are cached into composer cache-folder the first time downloaded. So no HTTP Request to download the zip-files will be done on second run - just the unzip. Running this on a current project with 72 dependencies in 44 different languages, the wp-translation-downloader-part runs in ~15 seconds on Windows 10. 
Can you please run `composer update -vvv` (second run) to see if cache is actually used? And how many languages are you using? It should look like following:

```
[CACHED] C:/Users/*******/AppData/Local/Composer/translations/wordpress-seo-zh_CN-15.9.2.zip
    ✓ 15.9.2 | zh_CN
```

**Comment by johnbillion** [comment]
Ah I think I saw the `auto-run` option but didn't realise what it did. That suits our workflow, thanks.
