### ISSUE TITLE
Allow to change `auto-run` value from an environment variable

### ISSUE THREAD

**Issue by benoitchantre** [inpsyde/wp-translation-downloader#14]
**Is your feature request related to a problem? Please describe.**
I’m trying to optimize some steps in a CI context.
The download of translations take is not necessary for some jobs (ex: coding standards checks).

**Describe the solution you'd like**
I would like to be able to disable the download of translations for specific CI jobs, and I think that the usage of an environment variable to modify the `auto-run` behavior would be a good solution.

**Describe alternatives you've considered**
An alternative to that could be to use another composer file with the `auto-run` config set to false for these CI jobs that don’t require the download of translation files, but that would be more complicated to maintain.

**Comment by Chrico** [comment]
Hm...sounds reasonable to use env-vars for configuration. But this would mean i need to support all configurations via env vars. Hm...we could also allow supporting env-based configurations via json files. Something like `wp-translation-downloader.json` (default) and will be merged with `wp-translation-downloader.{env}.json`. But this sounds like a lot overhead and i've no real use case (aside from `auto-run`) where merging/overwriting configurations makes sense.

Tbh, I still don't like the `auto-run`-feature. This is some leftover from early days and i should probably just delete it in a new major version... 😬 What we normally do in every project, we set `auto-run` to `false` and have an own step in Github Actions (same applies for other runners) which runs the translation downloading.

**Comment by benoitchantre** [comment]
Thank you for your feedbacks.

The idea behind using env var is to keep the default behaviour for the developer, but to be able to change it in another context like a CI environment.

Maybe it's easier and better to set the `auto-run` as `false` as you do, to add a step in GitHub Actions and to update manually when necessary in the local environment. If you forget to update translations in your local environment, that's not a big issue.
