### ISSUE TITLE
Add support for TranslationsPress

### ISSUE THREAD

**Issue by benoitchantre** [inpsyde/wp-translation-downloader#15]
**Is your feature request related to a problem? Please describe.**
Gravity Forms has removed the languages files from their package since version 2.5.0
They now use [TranslationsPress](https://translationspress.com/) to manage their translations which is apparently not based on GlottPress.

**Describe the solution you'd like**
Whould it be possible to some sort of support for TranslationsPress?

Related links that could help :
- https://translationspress.com/documentation/developers/project-integrations/
- https://packagist.org/packages/wp-transaltions/t15s-registry

**Describe alternatives you've considered**
I have tried to download the translations with WP-CLI without success.
I'm now using curl and unzip in my deployment workflow, but there should be a better way to handle that.

**Comment by Chrico** [comment]
Hey ☕ 

We're downloading Gravityforms translations as well via `inpsyde/wp-translation-downloader`. As far as i can see TranslationPress is also using the same response as GlotPress does. 

We have configured in our `wp-translation-downloader.json` following:

```json
{
    "auto-run": false,
    "api": {
        "names": {
            "inpsyde-mirror/gravityforms": "https://packages.translationspress.com/rocketgenius/gravityforms/packages.json"
        }
    },
    "directory": "languages",
    "languages": [
          "de_DE"
    ]
}
```

You need to adapt the ` "inpsyde-mirror/gravityforms"` to yours, i don't know how you ship Gravityforms in your composer.json :)

**Comment by benoitchantre** [comment]
Thank you for this detailed and helpful answer!

I use [Release Belt](https://github.com/Rarst/release-belt) with premium plugins like Gravity Forms. I have also tried SatisPress but some plugins cannot be activated at the same files. Curious to know what solution you use.

**Comment by Chrico** [comment]
We're using a WordPress multisite with SatisPress, where we group plugins like "all WooCommerce-plugins go into a blog 1", "All Gravityforms-plugins go into blog 2" and so on. Works at least in terms of "compatibility" and nothing breaks...but that multisite is slow as hell thanks to all those "premium Plugins"....at least it fullfills its purpose. 😬 A server cron takes care of running the WP Cron to get updates for those plugins in all blogs.

**Comment by benoitchantre** [comment]
Thank you for these infos. I did the same thing with SatisPress but wasn't convinced enough to replace Release Belt, even with the multisite configuration (much better than an single installation, but it is not possible to get automated updates without a network activation).
