### ISSUE TITLE
Is PHP 8 supported?

### ISSUE THREAD

**Issue by benoitchantre** [inpsyde/wp-translation-downloader#18]
In `composer.json`, I see `"php": ">=7.1"` as requirement, but the unit tests matrix doesn't have PHP 8 or PHP 8.1.

If PHP 8 and PHP 8.1 are not supported, `composer.json` should indicate a requirement like that : `"php": "^7.1"`.

**Comment by Chrico** [comment]
Hey ☕  right now i'm using it locally with PHP 8.0 and it works. So we might can adapt the composer.json and Github workflows to cover PHP 7 and 8.
