### ISSUE TITLE
Cannot use with latest bedrock because it requires `composer/installers: ^2.0`

### ISSUE THREAD

**Issue by calind** [inpsyde/wp-translation-downloader#19]
Latest bedrock requires `composer/installers: ^2.0` so `wp-translation-downloader` fails installing with:
```
  Problem 1
    - Root composer.json requires inpsyde/wp-translation-downloader ^2.0 -> satisfiable by inpsyde/wp-translation-downloader[2.0, ..., 2.0.4].
    - inpsyde/wp-translation-downloader[2.0, ..., 2.0.4] require composer/installers ^1.6 -> found composer/installers[v1.6.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0).
```

**Comment by gmazzap** [comment]
@Chrico I think changing the requirements from ` "composer/installers": "^1.6"` to ` "composer/installers": "^1.6 || ^2"` should be straightforward and don't cause any issue.

We don't really use code from ` composer/installers`, even assuming there're BC breaks in code... that'll be unrelevant for us.
