### ISSUE TITLE
Core Translations

### ISSUE THREAD

**Issue by MaximeCulea** [inpsyde/wp-translation-downloader#3]
Hio :wave:

Awesome work here ;)

I wanted to request you a new feature, as WordPress is also installed with Composer and it's like a "WordPress Package", it could be usefull to download the core translations for a fresh install and/or updating core.

What do you think about that?

Thx

**Comment by MaximeCulea** [comment]
In fact, it's already implemented ^^ looking into the classes and the one for core translations. But on the install there is no core tranlsations downloaded :/

**Comment by tyrann0us** [comment]
Hi @MaximeCulea,
yes, translations will be installed also for WordPress core. For this to work, the WordPress Composer package must be of type `wordpress-core`.

Which package do you use? With [`johnpbloch/wordpress`](https://github.com/johnpbloch/wordpress) it works for me:
```
% composer require johnpbloch/wordpress                         
Using version ^5.3 for johnpbloch/wordpress
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing johnpbloch/wordpress-core-installer (1.0.2): Loading from cache
  - Installing johnpbloch/wordpress-core (5.3.2): Loading from cache
    - [OK] Installed translation files | plugin wordpress-core | version 5.3.2 | language de_DE.
    - [OK] Installed translation files | plugin wordpress-core | version 5.3.2 | language de_DE_formal.
    - [OK] Installed translation files | plugin wordpress-core | version 5.3.2 | language es_ES.
  - Installing johnpbloch/wordpress (5.3.2): Loading from cache
Writing lock file
Generating optimized autoload files
[…]
```

**Comment by MaximeCulea** [comment]
Thank you for the quick update ! 
I’ll check this out, maybe my custom install not configured well.

**Comment by MaximeCulea** [comment]
I had no internet while I was installing / initializing my project. Now I have, even languages are setted in the composer.json : 
```
 "wp-translation-downloader": {
    "languages": [
          "fr_FR"
    ],
    "directory": "web/app/languages"
 }
```
The package is warning me it is not setted, resulting in all languages to be downloaded :/
Any idea if I am doing something wrong?

**Comment by MaximeCulea** [comment]
Ok, so to add some new elements, here what is happening in my workflow during the composer create project :

1. ask for languages
![Untitled_ Jan 7 2020 1_52 PM - Edited - Edited](https://user-images.githubusercontent.com/5576409/71897372-b1e8e480-3156-11ea-82e6-6a0e38757959.gif)

2. the composer.json is correctly edited depending on the choice(s)
![Untitled_ Jan 7 2020 1_52 PM - Edited](https://user-images.githubusercontent.com/5576409/71897401-c4631e00-3156-11ea-94ec-dca446b231c9.gif)

3. when it goes to the package part, it doest not understand the extra provided, trigerring the **extra.wp-translation-downloader.languages has to be configured as non empty array in your composer.json** error. It also goes into downloading all the languages for wp core (for exemple).
![Untitled_ Jan 7 2020 1_52 PM - Edited (1)](https://user-images.githubusercontent.com/5576409/71897414-cf1db300-3156-11ea-829c-feb50a7810fb.gif)

In advance, thank you so much for your help :)

**Comment by Chrico** [comment]
Howdy @MaximeCulea .

Sry for the late response, but its for me the first week of work this year ;) 

Can you pls provide your full `composer.json` ? I guess something is interfering with the package. 

Also i can see in your last give some selection for _"WP Languages: language(s) of the site?"_ - this looks very suspicious to me, since it's kind of named similar to our package naming schema, but is definitely not from us :)

**Comment by MaximeCulea** [comment]
Hi @Chrico, thank you for your time to respond.

> Can you pls provide your full composer.json ? I guess something is interfering with the package.

I could send ii to you but not as public one :)

> Also i can see in your last give some selection for "WP Languages: language(s) of the site?" - this looks very suspicious to me, since it's kind of named similar to our package naming schema, but is definitely not from us :)

It's definitely not you. I've done a command that prompt and ask the languages by adding at 
`post-root-package-install` the command 
```json
"set-project-lang":[
			"WIDE\\ComposerScripts\\WPLanguages::set_project_languages"
		],
```
that lunch the following script [WPLanguages.php](https://github.com/inpsyde/wp-translation-downloader/files/4078004/WPLanguages.php)

**Comment by Chrico** [comment]
Ping me in WordPress-Slack (ChriCo / Christian Leucht) or send me an E-Mail c.leucht@inpsyde.com and i'll try to have a look at it! :)

**Comment by MaximeCulea** [comment]
I was looking forward to check if the 1.1.3 could work better in my use case, but found that core download is still break #6 :'(

**Comment by MaximeCulea** [comment]
Now the 2.0.2 is working fine 👌
